<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('certificates', function (Blueprint $table) {
            $table->id();
            $table->string('certificate_code')->unique();
            
            // Relations
            $table->unsignedBigInteger('result_id');
            $table->unsignedBigInteger('competition_id');
            
            // Recipient Info
            $table->string('student_name');
            $table->string('school_name');
            $table->string('competition_name');
            
            // Level & Rank
            $table->enum('level', ['group', 'district']);
            $table->integer('rank');
            $table->enum('medal', ['gold', 'silver', 'bronze', 'participant'])->default('participant');
            
            // Judges & Committee (JSON)
            $table->json('judges')->nullable();
            $table->json('committee')->nullable();
            
            // Signatory
            $table->string('signed_by')->nullable(); // ผู้ลงนาม
            $table->string('signer_position')->nullable(); // ตำแหน่ง
            
            // PDF
            $table->string('pdf_path')->nullable();
            $table->date('issue_date');
            
            // Generated By
            $table->unsignedBigInteger('generated_by')->nullable();
            $table->timestamp('generated_at')->nullable();
            
            $table->timestamps();
            
            // Indexes
            $table->index('certificate_code');
            $table->index('result_id');
            $table->index('level');
            $table->index('issue_date');
            
            // Foreign Keys
            $table->foreign('result_id')->references('id')->on('results')->onDelete('cascade');
            $table->foreign('competition_id')->references('id')->on('competitions')->onDelete('cascade');
            $table->foreign('generated_by')->references('id')->on('users')->onDelete('set null');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('certificates');
    }
};
